language: java
jdk:
  - oraclejdk10
deploy:
  provider: releases
  api_key:
    secure: WPYyNfb1Brr+cH/5gGhGX4gSriuK9lPRV3buEQZEDFU61D9cOlNJ/0ipdsu+kndOcoIbgVqPkMueJWhySnPyuomc102UOEx4gMKdM62dF63JmZEnVKL2wrMlzrNOBt+CnqCU9ByEgzrDPzjirBpSjsHjuOxDc17sF8EXOvVqNzzkg5wTkrY9e3yGqt8kYWHVpjn9WU4TFnF6I1728+/SutP4alcO6MO+fDro9gwEtJhx6ezT30/CsqBuZUyVpfpi+JrgXopVNkzVR+Z9CLJr3wYm5JkxSU6vx1PYhoyN/XUnFWfQPWfcYtPQDoW92YuSls5T9c4BqMNIt9YheY8CYZaUM+mBI1EqrO8czrTt2sHPmsEl3Cv0MKd12vWpZGOQl42jk8vJkVwSUc/Y2zkEFECkwKu9HAkq61RA+9Yh8Zz+tjzzUX0PWeJANdd7F37GTyaXppRb+RQ/lUOW9m+lXbWp9G0Q6Id8dj6Baz5Wxm9t7DASWNogd80y4Tg6vgDLz1ZpvvyUST0mZm8GPRQrXva9jSP43v2Z18TgErjbfA52u1N2v48tvvPlhN3b34TPDvOMpSatQ758iwMdlOFWAOO+XXb9kNsfBOPgPM0aKbhFcI3hz3klGdxjcgQUoXUUFntJnsEE4Zed78sgIj2JCDXihhx8FYM0dqiCb0huZuc=
  file: target/PocketVote.jar
  skip_cleanup: true
  on:
    repo: ProjectInfinity/PocketVote-Nukkit
    tags: true