name: ${name}
main: ${groupId}.${artifactId}
author: ProjectInfinity
version: ${version}
api: ["1.0.0"]
description: Simple, elegant and efficient voting suite.
permissions:
  pocketvote.admin:
    default: op
    description: "Allows user to administer pocketvote"
  pocketvote.vote:
    default: true
    description: "Allows a player to use the /vote command"